import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@/components/store/Footer";
import { NewsLetter } from "@/components/store/NewsLetter";
import { CartProvider } from "@/context/CartContext";
import { Header } from "@/components/store/Header";
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react";
import { WishlistProvider } from "@/context/WishlistContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
          <WishlistProvider>
            <CartProvider>
              <Header />
              {children}
            </CartProvider>
          </WishlistProvider>
        
        <NewsLetter />
        <Footer />
      </body>
    </html>
  );
}
