import React, { Suspense } from "react";
import { Hero } from "./Hero";
import { Features } from "./Features";
import { Banner } from "./Banner";
import { ProductCategory } from "./ProductCategory";
import type { Metadata } from "next";
import { BestSelling } from "./BestSelling";

export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <main>
      <Hero />
      <div className="max-w-[1116px] mx-auto">
        <Features />
        <Suspense>
          <BestSelling />
        </Suspense>
      </div>
      <Banner />
      <Suspense>
        <ProductCategory />
      </Suspense>
    </main>
  );
};

export default page;
